export interface Exercise {
  id: string;
  name: string;
  sets: number;
  reps: string;
  rir: string;
  rest: string;
  note: string;
  videoQuery: string;
}

export interface WorkoutDay {
  id: string;
  name: string; // e.g., "Lunes - Pecho/Tríceps"
  dayOfWeek: number; // 1 = Monday, etc.
  exercises: Exercise[];
}

export const routine: WorkoutDay[] = [
  {
    id: "monday",
    name: "Lunes - Pecho/Tríceps",
    dayOfWeek: 1,
    exercises: [
      {
        id: "press-inclinado-barra",
        name: "Press inclinado barra",
        sets: 4,
        reps: "6–8",
        rir: "1–2",
        rest: "3 min",
        note: "Excéntrica 3s",
        videoQuery: "press inclinado barra tecnica",
      },
      {
        id: "press-plano-mancuernas",
        name: "Press plano mancuernas",
        sets: 3,
        reps: "8–10",
        rir: "1",
        rest: "2 min",
        note: "Estiramiento completo",
        videoQuery: "press plano mancuernas tecnica",
      },
      {
        id: "aperturas-inclinadas",
        name: "Aperturas inclinadas",
        sets: 3,
        reps: "12–15",
        rir: "0–1",
        rest: "60 s",
        note: "Pausa 1s abajo",
        videoQuery: "aperturas inclinadas mancuernas tecnica",
      },
      {
        id: "fondos",
        name: "Fondos",
        sets: 3,
        reps: "8–12",
        rir: "1",
        rest: "2 min",
        note: "Inclinación ligera",
        videoQuery: "fondos paralelas pecho tecnica",
      },
      {
        id: "extension-triceps-cuerda",
        name: "Extensión tríceps cuerda",
        sets: 3,
        reps: "12–15",
        rir: "0–1",
        rest: "60 s",
        note: "Última drop set",
        videoQuery: "extension triceps cuerda tecnica",
      },
    ],
  },
  {
    id: "tuesday",
    name: "Martes - Espalda/Bíceps",
    dayOfWeek: 2,
    exercises: [
      {
        id: "jalon-pecho-ancho",
        name: "Jalón al pecho ancho",
        sets: 4,
        reps: "8–12",
        rir: "1",
        rest: "2 min",
        note: "Pausa 1s abajo",
        videoQuery: "jalon al pecho agarre ancho tecnica",
      },
      {
        id: "remo-barra",
        name: "Remo con barra",
        sets: 4,
        reps: "8–10",
        rir: "1–2",
        rest: "3 min",
        note: "Pausa arriba",
        videoQuery: "remo con barra tecnica",
      },
      {
        id: "pullover-polea",
        name: "Pullover en polea",
        sets: 3,
        reps: "12–15",
        rir: "0–1",
        rest: "60 s",
        note: "Foco dorsal",
        videoQuery: "pullover polea alta tecnica",
      },
      {
        id: "face-pull",
        name: "Face pull",
        sets: 3,
        reps: "15–20",
        rir: "0",
        rest: "45 s",
        note: "Control total",
        videoQuery: "face pull tecnica",
      },
      {
        id: "curl-barra-z",
        name: "Curl barra Z",
        sets: 3,
        reps: "8–10",
        rir: "1",
        rest: "90 s",
        note: "Sin balanceo",
        videoQuery: "curl barra z tecnica",
      },
      {
        id: "curl-inclinado",
        name: "Curl inclinado",
        sets: 3,
        reps: "12–15",
        rir: "0–1",
        rest: "60 s",
        note: "Estiramiento largo",
        videoQuery: "curl inclinado mancuernas tecnica",
      },
    ],
  },
  {
    id: "wednesday",
    name: "Miércoles - Pierna",
    dayOfWeek: 3,
    exercises: [
      {
        id: "prensa-inclinada",
        name: "Prensa Inclinada (Leg Press)",
        sets: 4,
        reps: "8–10",
        rir: "1",
        rest: "3 min",
        note: "Rango completo, sin rebotar",
        videoQuery: "prensa inclinada piernas tecnica",
      },
      {
        id: "sentadilla-hack-bulgara",
        name: "Sentadilla Hack o Búlgara",
        sets: 3,
        reps: "10–12",
        rir: "1",
        rest: "2 min",
        note: "Control excéntrico",
        videoQuery: "sentadilla hack o bulgara tecnica",
      },
      {
        id: "extension-cuadriceps",
        name: "Extensión de Cuádriceps",
        sets: 4,
        reps: "12–15",
        rir: "0",
        rest: "90 s",
        note: "Baja en 3s, aprieta arriba",
        videoQuery: "extension cuadriceps maquina tecnica",
      },
      {
        id: "curl-femoral",
        name: "Curl Femoral (Tumbado)",
        sets: 4,
        reps: "10–12",
        rir: "1",
        rest: "90 s",
        note: "Pausa 1s al contraer",
        videoQuery: "curl femoral tumbado tecnica",
      },
      {
        id: "elevacion-pantorrilla",
        name: "Elevación de Pantorrilla",
        sets: 4,
        reps: "15–20",
        rir: "0",
        rest: "60 s",
        note: "Pausa 1s estirando abajo",
        videoQuery: "elevacion pantorrilla maquina tecnica",
      },
    ],
  },
  {
    id: "thursday",
    name: "Jueves - Hombro/Core",
    dayOfWeek: 4,
    exercises: [
      {
        id: "press-militar-barra",
        name: "Press militar barra",
        sets: 4,
        reps: "5–6",
        rir: "1–2",
        rest: "3 min",
        note: "Core firme",
        videoQuery: "press militar barra tecnica",
      },
      {
        id: "elevaciones-laterales",
        name: "Elevaciones laterales",
        sets: 4,
        reps: "15–20",
        rir: "0–1",
        rest: "45 s",
        note: "Balanceo controlado",
        videoQuery: "elevaciones laterales mancuernas tecnica",
      },
      {
        id: "laterales-polea",
        name: "Laterales en polea",
        sets: 3,
        reps: "12–15",
        rir: "0",
        rest: "60 s",
        note: "Tensión continua",
        videoQuery: "elevaciones laterales polea tecnica",
      },
      {
        id: "pajaros-posterior",
        name: "Pájaros/posterior",
        sets: 4,
        reps: "15–20",
        rir: "0",
        rest: "45 s",
        note: "Contracción 1s",
        videoQuery: "pajaros mancuernas posterior tecnica",
      },
      {
        id: "elevaciones-piernas",
        name: "Elevaciones de piernas",
        sets: 4,
        reps: "12–15",
        rir: "0",
        rest: "45 s",
        note: "Sin balanceo",
        videoQuery: "elevaciones de piernas colgado tecnica",
      },
      {
        id: "crunch-polea",
        name: "Crunch polea",
        sets: 3,
        reps: "15–20",
        rir: "0",
        rest: "45 s",
        note: "Fuerte contracción",
        videoQuery: "crunch abdominal polea alta tecnica",
      },
    ],
  },
  {
    id: "friday",
    name: "Viernes - Torso/Brazos",
    dayOfWeek: 5,
    exercises: [
      {
        id: "press-maquina-smith",
        name: "Press máquina/Smith",
        sets: 3,
        reps: "10–12",
        rir: "1",
        rest: "2 min",
        note: "Movimiento constante",
        videoQuery: "press pecho maquina smith tecnica",
      },
      {
        id: "cruces-polea",
        name: "Cruces en polea",
        sets: 3,
        reps: "15",
        rir: "0",
        rest: "60 s",
        note: "Aprieta al centro",
        videoQuery: "cruces polea pecho tecnica",
      },
      {
        id: "jalon-neutro",
        name: "Jalón neutro",
        sets: 3,
        reps: "10–12",
        rir: "1",
        rest: "2 min",
        note: "Control",
        videoQuery: "jalon al pecho agarre neutro tecnica",
      },
      {
        id: "remo-sentado",
        name: "Remo sentado",
        sets: 3,
        reps: "12–15",
        rir: "0–1",
        rest: "90 s",
        note: "Pausa 1s",
        videoQuery: "remo sentado polea baja tecnica",
      },
      {
        id: "curl-predicador",
        name: "Curl predicador",
        sets: 3,
        reps: "10–12",
        rir: "1",
        rest: "90 s",
        note: "Baja lento",
        videoQuery: "curl predicador barra z tecnica",
      },
      {
        id: "press-frances",
        name: "Press francés",
        sets: 3,
        reps: "8–10",
        rir: "1",
        rest: "90 s",
        note: "Control de codos",
        videoQuery: "press frances barra z tecnica",
      },
    ],
  },
];
